### ISSUE TITLE
The black area of time changed in size over time

### ISSUE THREAD

**Issue by AbdelmalekBouguerra** [DBChoco/Muezzin#11]
### **Alsalam w ealaykum w rahmat allah w barakatuh ramadan mubarak.**
I did notice this when using the application it not a big deal but if it is fixed it will give more elegance to your application.
I love your work very useful for my use case. thank you for you eforts , god bless you.

![Nouveau projet](https://user-images.githubusercontent.com/64624629/165017205-2f8edb03-dc28-4c36-8d1a-adc035419585.png)

**Comment by AbdelmalekBouguerra** [comment]
yes brother it will be much better.
of course you have created a modern and easy to use app, nothing like it in the market as far as i know.
wafaqak allah.

**Comment by AbdelmalekBouguerra** [comment]
same thing here if you maybe write the time in a new line, it won't change the size of the area over time.
![image](https://user-images.githubusercontent.com/64624629/165139889-d9569227-29ac-422f-9ef4-515fefc36b61.png)

**Comment by DBChoco** [comment]
You may be right brother, even though I don't like it very much to be honest. However if I'm going to do it it's probably going to be quite the hassle because I'd need to take into consideration multiple things:

- The size of the screen & thus the font size
- The font used (Arabic and Bengali have their own font)
- The time format (24 or 12 hours)
- The language (some languages have longer words for the "Time until X" part)

You are right that the fact that it moves each second may be disturbing, but to fix that, you can disable the seconds in the settings, it'll become much more static. Perhaps that might be to your liking. What do you think brother ?

**Comment by AbdelmalekBouguerra** [comment]
true it helps a lot, i didnt search in the options my bad.
very well made thank you a lot.
Jazzaka Lahu khairan

**Comment by DBChoco** [comment]
No problem brother, if you have any other issues or questions you can always ask.
Wa iyak Jazzaka Lahu khairan!

**Comment by meypod** [comment]
@DBChoco you can use a monospace variant of the font you use (if it has, or another font if it does not have) for the numbers part
simply wrap the numbers in a <span> or <div> and apply the monospace font only to it
this will help the issue and wont require changing the overall look significantly

**Comment by DBChoco** [comment]
![image](https://github.com/DBChoco/Muezzin/assets/44785461/0feca09c-6b5a-4293-9181-106bd20ed467)
Very nice suggestion brother, I didn't know it existed. Jazzaka Lahu khairan; how do you like it ?

**Comment by meypod** [comment]
It would be nice if you could find a similar font with monospace variant of it for a more unified look
or change the main fonts to something that also has a monospace variant

but it looks ok now as well, the most important part for myself was to prevent text from moving from it's place when it changes

nice work

**Comment by DBChoco** [comment]
The thing is that I really like the Quicksilver font (the main one) so I don't want to change it. InshaAllah I'll try to find some other monospace font that is similar or at least compatible.

**Comment by DBChoco** [comment]
Thanks to Allah and this website I managed to convert the font I used to monospace https://graphicdesign.stackexchange.com/questions/10644/how-can-i-make-a-font-monospaced, now it should be pretty uniform: 
![image](https://github.com/DBChoco/Muezzin/assets/44785461/40873ba1-b4b7-4e3e-9c3a-33040382211b)
The "1" is a bit small and it's quite awkward to have it take so much space, but it's better than to have it move all over.

**Comment by meypod** [comment]
nice
looks good

**Comment by DBChoco** [comment]
It's good that you like it, I'll inshaAllah close the issue once I push all the changes.

**Comment by meypod** [comment]
It may be a good idea to apply it to the prayer times in the table, they will look aligned
but it doesn't matter much as they don't move

**Comment by DBChoco** [comment]
Truly nice idea, I didn't think about it even for a second !
This is how it looks and Alhamdoulillah I think it looks awesome:
![image](https://github.com/DBChoco/Muezzin/assets/44785461/3fb01c4c-6d7d-467f-a052-8e710fd1daed)

**Comment by DBChoco** [comment]
Fixed with this https://github.com/DBChoco/Muezzin/commit/4ba09484388d298ff636eeb020d7802edb0f64ad
Jazzaka Lahu khairan
