### ISSUE TITLE
Messed up prayer times display

### ISSUE THREAD

**Issue by dakh7** [DBChoco/Muezzin#12]
Runs fine for maybe a day but on a computer running 24/7 and a laptop that I close the lid and goes to sleep and wakes up regularly, the time displayed eventually ends up being messed up, trying to show the next Fajr time (even though the next prayer time is not Fajr) and not correctly - looks like it tries to show a range of time for hours, minutes, and seconds - no matter the time of day and the Azan does not play. 

Desktop runs on Windows 11 and Laptop on Windows 10. Screenshots attached. Two are from when it messed up and one is when it is first run.

![Muezzin App - days later, 24-7 running desktop pc - incorrect time](https://user-images.githubusercontent.com/20505986/174700992-2a4d9f0e-e2dc-4bfa-b43e-e793d9debd63.png)
![Muezzin App - days later, wake from sleep laptop - incorrect time](https://user-images.githubusercontent.com/20505986/174700993-29973487-0db9-46c2-82fe-c9520cf51614.png)
![Muezzin App - Fresh Install - Correct Time](https://user-images.githubusercontent.com/20505986/174700994-f3cfcb96-e68d-4e07-a809-369dce83a02c.png)

**Comment by DBChoco** [comment]
Just noticed an error in the part of the code that reloads the app at midnight, so I fixed that, but I don't know if it will be enough.
https://github.com/DBChoco/Muezzin/commit/20529aeec321a5add0ad784ce5c486732d861e69

**Comment by dakh7** [comment]
Sorry to take so long getting back to you, basically leaving it on overnight and coming back the next day I noticed the Adhan didn't play at the prayer times in the app, and then opening the main window from the system tray it showed the incorrect times as above. 

This happened if the PC it was running on was asleep (laptop) or stayed on the entire time (desktop). I'm not sure how long it took for it to stop functioning, usually I noticed it play the previous night when I first started the app and then the next day when I either turned the laptop on (from sleep) or was in the room the desktop was in, they just didn't play the Adhan.

**Comment by DBChoco** [comment]
Okay, I'll see if this is enough then. InshaAllah we'll figure it out.
Jazzaka Lahu khairan.

**Comment by dakh7** [comment]
If it helps, I just noticed that if I go to settings and return back (no changes made), it looks like the times get corrected.

**Comment by dakh7** [comment]
Tried the new version, 2.5.9, and it seems to have fixed the issue, Displaying the correct time and playing the Azan on schedule as it is supposed to, only tested on a windows 11 PC though. Closing this issue.
