### ISSUE TITLE
Add auto-theme, auto-language and auto-time format

### ISSUE THREAD

**Issue by alfus5** [DBChoco/Muezzin#13]
Hi, I discovered your project today and I like it a lot.

Here are the features and fixes I recommend you to implement:
- allow Muezzin to determine automatically the theme of the device ( dark mode or light mode )
- allow Muezzin to automatically determine the language of the device (English, Arabic, Spanish, French, Russian, etc.)
- create a [.MSI](https://www.youtube.com/watch?v=DWY6UAiJmnM) installer for Muezzin to facilitate installation and uninstallation.

thank you for your incredible work and may Allah support you in your project

**Comment by DBChoco** [comment]
Jazzaka Lahu khairan for the support and suggestions.
I'll keep them in mind brother, perhaps someday I might add these.
I don't know when I'll get the time though.

**Comment by DBChoco** [comment]
Assalam Alaykoum,
Sorry it took a long time for the updates, motivation is running low here hahaha
Here is the MSI update: https://github.com/DBChoco/Muezzin/commit/bc5ea85ca0fc2d6f4206afacb7f99e6c8ba7cad0
And here are the auto-theme and auto-language updates: https://github.com/DBChoco/Muezzin/commit/97c6b3181cd969445b4bb6c88e5f4b64a4a16cd5

InshaAllah I plan on releasing this new update (2.5.9) by the end of this week inshaAllah

**Comment by DBChoco** [comment]
All added here Alhamdoulillah,
Jazzaka Lahu khairan for the suggestions.
