### ISSUE TITLE
Quran Play Resume/Replay Issue

### ISSUE THREAD

**Issue by rahidulislam** [DBChoco/Muezzin#14]
I will listen Quran with clicking play button. when I click Stop button this will stop,  again I click play button this start from first line of Surah. Please Add resume Button so that We will stop for some times and replay from last stop.

**Comment by DBChoco** [comment]
Jazaka Lahu khairan it's a very nice idea, I'll have a look into it inshaAllah

**Comment by DBChoco** [comment]
Here is is akhi, I added a small forward button in the quran app
![image](https://user-images.githubusercontent.com/44785461/186418877-722bc560-f381-40ea-8559-2d84157100c6.png)
https://github.com/DBChoco/Muezzin/commit/cf01ff78ca97dc9a9e2d2c414f921f3bc84124e9

InshaAllah the changes will be applied on the next update. I'm still waiting for big changes to push it so you might have to wait a while. I apologize for that.
