### ISSUE TITLE
Quran does not Playing

### ISSUE THREAD

**Issue by rahidulislam** [DBChoco/Muezzin#15]
Quran does not playing in elementary OS 6.1
![Screenshot from 2022-08-24 18-02-19](https://user-images.githubusercontent.com/33887458/186413609-36ac0eef-66da-4ff0-80f0-bcb578a594a5.png)

**Comment by DBChoco** [comment]
Salam, can you open the developer tools and see if there is any error messages ?
I believe you can open it with crtl+shift+i.
Does this happen every time ?

**Comment by rahidulislam** [comment]
Some error shows in developer Tools. Icon does not showing in dock of elementary os 6.1
![Screenshot from 2022-08-25 17-42-26](https://user-images.githubusercontent.com/33887458/186655867-3ec87a6b-4344-4cfb-9c90-23778621d9a3.png)
![Screenshot from 2022-08-25 17-43-39](https://user-images.githubusercontent.com/33887458/186655876-ca2abe65-97c7-4cff-99e2-dbd644b1716d.png)
![Screenshot from 2022-08-25 17-44-03](https://user-images.githubusercontent.com/33887458/186655880-83e137b6-12e9-4e01-ad9b-ea3dd3267492.png)
![Screenshot from 2022-08-25 17-41-14](https://user-images.githubusercontent.com/33887458/186655857-750fb72a-f3ef-4e73-bbfc-32f81a542740.png)

**Comment by DBChoco** [comment]
Could you try to reset all settings ? 
Press Alt, then go to File, then "Reset settings"
It seems like the issue is with the Quran settings not being saved properly, or that they are not initialized at all.
