### ISSUE TITLE
any plan to support shia timing?

### ISSUE THREAD

**Issue by rezad1393** [DBChoco/Muezzin#16]
I see that in madhab method there is shafi and hanafi.
is there any plan to calculate for shia in iran?
thank you.

**Comment by DBChoco** [comment]
Assalam Alaykoum
Doesn't the "Tehran" option in 'Advanced' > 'Calculation Methods' work ?

**Comment by rezad1393** [comment]
علیکم سلام

I am not a religious scholar so I may be in ignorance but I remember that just using tehran in other apps would only calculate addan timing based on sunni method and I think there was a small difference.
like this:
https://islam.stackexchange.com/questions/11138/why-is-there-a-difference-in-prayer-time-between-shia-and-sunni


also I use you app on linux with wayland desktop on kde.
sometimes the tray icon gets unresponsive and I cant close it normally.

also, thank you for the open source application and may God reward you in this word and the next.

**Comment by DBChoco** [comment]
Assalam Alakoum,
Changing to the Tehran method uses these calculation angles: 
![image](https://user-images.githubusercontent.com/44785461/200127805-f53cfe7e-2360-408f-b790-a965f10bbc3b.png)

The API that I use to calculate the prayer times is called [Adhan-JS](https://github.com/batoulapps/adhan-js), and there are no specific Shia calculation methods there. I've never heard of anything like that either.

Perhaps you could play with the settings (calculation angles, delays, etc.) to make the timings match your local mosque. You can customize the app to your liking.

For the tray icon, I've never tested it on Wayland but I can see on the internet that Electron does have some bugs on Wayland, we can only patiently wait for Electron to be fixed, sorry about that.

Ameen brother, May Allah guide us all to do great things.

**Comment by rezad1393** [comment]
thank you.
I will close this.
