### ISSUE TITLE
Persian language

### ISSUE THREAD

**Issue by Oliver-Mahdi** [DBChoco/Muezzin#20]
Hi I really like your windows app but can you add Persian language to it ?    I can help if needed
thanks.

**Comment by DBChoco** [comment]
Assalam Alaykoum,
Sure, could you try an translate this please ?

```
fa: {
        'settings': 'Settings', //settingsTitle
        'language': 'Language', //langText
        'timeformat': 'Time format', //tfText
        '24hour': '24 Hour', //24hTimeFormatText
        '12hour': '12 Hour', //12hTimeFormatText
        'showSseconds': 'Show seconds', //showSecondsText
        'dateFormat': 'Date format', //dfText
        'dateFormat1': 'DD/MM/YYYY', //id="df1Text"
        'dateFormat2': 'MM/DD/YYYY', //id="df2Text"
        'dateFormat3': 'YYYY/MM/DD', //id="df3Text"
        'notifications': 'Notifications', //notifText
        'notifCheck': 'Enable notifications', //notifCheckText
        'coordinates': 'Coordinates', //coordinatesText
        'latitude': 'Latitude', //latText
        'longitude': 'Longitude', //lonText
        'timezone': 'Time zone', // tzText
        'adhan': 'Adhan', //adhanText and others in main
        'adhanCheck': 'Enable Adhan', //adhanCheckText
        'AdhanMecca': 'Adhan Mecca', //adhanMeccaText //Traduire juste Mecca
        'adhanAqsa': 'Adhan al-Aqsa', //adhanAqsaText
        'customAdhan': 'Custom Adhan', //customAdhanText
        'duaAfterAdhan': "Du'a after Adhan", //duaAfterText
        'theme': 'Theme', //themeText
        'darkMode': 'Dark Mode', //darkModeText
        'bgImage': 'Background Image', //bgImageText
        'bgImageCheck': 'Enable Background Image', //bgImageCheckText
        'calcMethods': 'Calculation Methods', //calcMethodsText
        'mwl': 'Muslim World League', //MWL
        'egyptian': 'Egyptian', //Egyptian
        'karachi': 'Karachi', //Karachi
        'uaq': 'Umm al-Qura', //UAQ
        'dubai': 'Dubai', //Dubai
        'qatar': 'Qatar', //Qatar
        'kuwait': 'Kuwait', //Kuwait
        'mc': 'Moonsighting Committee', //MC //pas traduire ça
        'singapore': 'Singapore', //Singapore
        'turkey': 'Turkey', //Turkey
        'tehran': 'Tehran', //Tehran
        'isna': 'ISNA (NA)', //ISNA
        'madhab': 'Madhab', //MadhabText
        'shafi': 'Shafi', //shafi
        'hanafi': 'Hanafi', //Hanafi
        'hlr': 'High Latitude Rule', //hlrText
        'motn': 'Middle of the Night', //MOTN
        'sotn': 'Seventh of the Night', //SOTN
        'ta': 'Twilight Angle', //TA
        'pcr': 'Polar Circle Resolution', //pcrText
        'cc': 'Closest City', //CC
        'cd': 'Closest Date', //CD
        'und': 'Do not calculate', //UND
        'shafaq': 'Shafaq', //ShafaqText
        'general': 'General', //shafaqG
        'ahmer': 'Red Twilight (ahmer)', //shafaqR
        'abyad': 'White Twilight (abyad)', //shafaqW
        'return': 'Return', //return
        'general': 'General', //v-pills-general-tab
        'location': 'Location', //v-pills-location-tab
        'audio': 'Audio', //v-pills-audio-tab
        'appearance': 'Appearance', //v-pills-appearance-tab
        'advanced': 'Advanced', //v-pills-advanced-tab
        'muezzin': 'Muezzin',
        'autoStart': 'Auto Start', //autoStartText
        'startAtLaunch': 'Start at launch', //autoStartCheckText
        'copyright': 'Copyright 2022, Muezzin, All rights reserved.', //copyright
        'quote': 'Indeed, prayer has been decreed upon the believers a decree of specified times.', //quote //à rechercher sur internet, la traduction sur internet est très mauvaise
        'source': "Qur'an: 4/103", //source
        'fajr': 'Fajr',
        'sunrise': 'Sunrise',
        'dhuhr': 'Dhuhr',
        'asr': 'Asr',
        'maghrib': 'Maghrib',
        'isha': 'Isha',
        'now': 'Now',
        'timeUntil': 'Time until',
        'startUpSound': 'Start Up Sound', //startUpSoundText
        'playSound': 'Play sound on startup', //startUpSoundText2
        'sysTray': 'System tray', //systrayText
        'minToTray': 'Minimize to tray', //systrayCheckText
        'customSettings': 'Custom settings', //customSettText
        'enableCS': 'Enable Custom Calculation Settings', //enableCalcText
        'fAngle': 'Fajr Angle', //fajrAngleText
        'mAngle': 'Maghrib Angle', //maghribAngleText
        'iAngle': 'Isha Angle', //ishaAngleText
        'delayAfterM': 'Delay after Maghrib', //delayText
        'delayMin': 'Delay (minutes)', //delayFormText
        'france': 'France', //France12 15 & 18
        'russia': 'Russia', //Russia
        'gulf': 'Gulf Region', //Gulf
        'preferences': 'Preferences', //menu label
        'resetSettings': 'Reset settings', //menu label
        'adjustements': 'Adjustments', //adjustmentsText
        'here': 'here',
        'enableAdj': 'Enable adjustments', //adjCheckText
        'fajrAdj': 'Fajr Adjustments', //fajrAdjText
        'dhuhrAdj': 'Dhurh Adjustments', //fajrAdjText
        'asrAdj': 'Asr Adjustments', //fajrAdjText
        'maghribAdj': 'Maghrib Adjustments', //fajrAdjText
        'ishaAdj': 'Isha Adjustments', //fajrAdjText
        'showSunnah': 'Show Sunnah times', //sunnahTimesText
        'motn': 'Middle of the night',  //MOTNCheckText
        'totn': 'Third of the night', //TOTNCheckText
        'minStart': 'Start minimized', //minStartCheckText
        'updateAvailable': 'Update available',
        'version': 'Version',
        'available': 'is available for download on GitHub',
        'download': 'Download',
        'later': 'Later',
        'quran': "Qur'an",
        'font': 'Font',
        'fontsize': 'Font size',
        'translation': 'Translation',
        'showTrans': 'Show translation',
        'diffLang': 'Different language from app',
        'transliteration': 'Transliteration',
        'showTransliteration': 'Show transliteration',
        'previous': 'Previous Surah',
        'next': 'Next Surah',
        'weather': 'Weather',
        'showWeather': 'Show weather',
        'units': 'Units',
        'celsius': 'Celsius',
        'kelvin': 'Kelvin',
        'fahrenheit': 'Fahrenheit',
        'playDua': "Play Du'a after Adhan",
        'open': 'Open',
        'quit': 'Quit',
        'ahmedNufeis': 'Ahmed Al-Nufais',
        'customFajr': 'Custom Fajr Adhan',
        'recitation': 'Recitation',
        'reciter': 'Reciter',
        "customTimes": "Custom Times",
        "enableCustomTimes" : "Enable custom times",
        "jumuah" : "Jumuah",
        "jumuahTime": "Jumuah Time",
        "enableJumuahTime": "Enable Jumuah Time",
        "shortAllahuAkbar": "Short sound - Mishary Rashid Alafasy",
        "hijriAdjTitle" : "Hijri date adjustments",
        "hijriAdjText" : "Hijri date difference",

    },

You have to translate what is after the : and between "" only. For example, on the first line, you should translate the "Settings".

Jazzaka Lahu khairan!
If you have any questions, don't hesitate

**Comment by Oliver-Mahdi** [comment]
thanks brother I will do it

**Comment by Oliver-Mahdi** [comment]
can

> Assalam Alaykoum, Sure, could you try an translate this please ?
> 
> ```
> fa: {
>         'settings': 'Settings', //settingsTitle
>         'language': 'Language', //langText
>         'timeformat': 'Time format', //tfText
>         '24hour': '24 Hour', //24hTimeFormatText
>         '12hour': '12 Hour', //12hTimeFormatText
>         'showSseconds': 'Show seconds', //showSecondsText
>         'dateFormat': 'Date format', //dfText
>         'dateFormat1': 'DD/MM/YYYY', //id="df1Text"
>         'dateFormat2': 'MM/DD/YYYY', //id="df2Text"
>         'dateFormat3': 'YYYY/MM/DD', //id="df3Text"
>         'notifications': 'Notifications', //notifText
>         'notifCheck': 'Enable notifications', //notifCheckText
>         'coordinates': 'Coordinates', //coordinatesText
>         'latitude': 'Latitude', //latText
>         'longitude': 'Longitude', //lonText
>         'timezone': 'Time zone', // tzText
>         'adhan': 'Adhan', //adhanText and others in main
>         'adhanCheck': 'Enable Adhan', //adhanCheckText
>         'AdhanMecca': 'Adhan Mecca', //adhanMeccaText //Traduire juste Mecca
>         'adhanAqsa': 'Adhan al-Aqsa', //adhanAqsaText
>         'customAdhan': 'Custom Adhan', //customAdhanText
>         'duaAfterAdhan': "Du'a after Adhan", //duaAfterText
>         'theme': 'Theme', //themeText
>         'darkMode': 'Dark Mode', //darkModeText
>         'bgImage': 'Background Image', //bgImageText
>         'bgImageCheck': 'Enable Background Image', //bgImageCheckText
>         'calcMethods': 'Calculation Methods', //calcMethodsText
>         'mwl': 'Muslim World League', //MWL
>         'egyptian': 'Egyptian', //Egyptian
>         'karachi': 'Karachi', //Karachi
>         'uaq': 'Umm al-Qura', //UAQ
>         'dubai': 'Dubai', //Dubai
>         'qatar': 'Qatar', //Qatar
>         'kuwait': 'Kuwait', //Kuwait
>         'mc': 'Moonsighting Committee', //MC //pas traduire ça
>         'singapore': 'Singapore', //Singapore
>         'turkey': 'Turkey', //Turkey
>         'tehran': 'Tehran', //Tehran
>         'isna': 'ISNA (NA)', //ISNA
>         'madhab': 'Madhab', //MadhabText
>         'shafi': 'Shafi', //shafi
>         'hanafi': 'Hanafi', //Hanafi
>         'hlr': 'High Latitude Rule', //hlrText
>         'motn': 'Middle of the Night', //MOTN
>         'sotn': 'Seventh of the Night', //SOTN
>         'ta': 'Twilight Angle', //TA
>         'pcr': 'Polar Circle Resolution', //pcrText
>         'cc': 'Closest City', //CC
>         'cd': 'Closest Date', //CD
>         'und': 'Do not calculate', //UND
>         'shafaq': 'Shafaq', //ShafaqText
>         'general': 'General', //shafaqG
>         'ahmer': 'Red Twilight (ahmer)', //shafaqR
>         'abyad': 'White Twilight (abyad)', //shafaqW
>         'return': 'Return', //return
>         'general': 'General', //v-pills-general-tab
>         'location': 'Location', //v-pills-location-tab
>         'audio': 'Audio', //v-pills-audio-tab
>         'appearance': 'Appearance', //v-pills-appearance-tab
>         'advanced': 'Advanced', //v-pills-advanced-tab
>         'muezzin': 'Muezzin',
>         'autoStart': 'Auto Start', //autoStartText
>         'startAtLaunch': 'Start at launch', //autoStartCheckText
>         'copyright': 'Copyright 2022, Muezzin, All rights reserved.', //copyright
>         'quote': 'Indeed, prayer has been decreed upon the believers a decree of specified times.', //quote //à rechercher sur internet, la traduction sur internet est très mauvaise
>         'source': "Qur'an: 4/103", //source
>         'fajr': 'Fajr',
>         'sunrise': 'Sunrise',
>         'dhuhr': 'Dhuhr',
>         'asr': 'Asr',
>         'maghrib': 'Maghrib',
>         'isha': 'Isha',
>         'now': 'Now',
>         'timeUntil': 'Time until',
>         'startUpSound': 'Start Up Sound', //startUpSoundText
>         'playSound': 'Play sound on startup', //startUpSoundText2
>         'sysTray': 'System tray', //systrayText
>         'minToTray': 'Minimize to tray', //systrayCheckText
>         'customSettings': 'Custom settings', //customSettText
>         'enableCS': 'Enable Custom Calculation Settings', //enableCalcText
>         'fAngle': 'Fajr Angle', //fajrAngleText
>         'mAngle': 'Maghrib Angle', //maghribAngleText
>         'iAngle': 'Isha Angle', //ishaAngleText
>         'delayAfterM': 'Delay after Maghrib', //delayText
>         'delayMin': 'Delay (minutes)', //delayFormText
>         'france': 'France', //France12 15 & 18
>         'russia': 'Russia', //Russia
>         'gulf': 'Gulf Region', //Gulf
>         'preferences': 'Preferences', //menu label
>         'resetSettings': 'Reset settings', //menu label
>         'adjustements': 'Adjustments', //adjustmentsText
>         'here': 'here',
>         'enableAdj': 'Enable adjustments', //adjCheckText
>         'fajrAdj': 'Fajr Adjustments', //fajrAdjText
>         'dhuhrAdj': 'Dhurh Adjustments', //fajrAdjText
>         'asrAdj': 'Asr Adjustments', //fajrAdjText
>         'maghribAdj': 'Maghrib Adjustments', //fajrAdjText
>         'ishaAdj': 'Isha Adjustments', //fajrAdjText
>         'showSunnah': 'Show Sunnah times', //sunnahTimesText
>         'motn': 'Middle of the night',  //MOTNCheckText
>         'totn': 'Third of the night', //TOTNCheckText
>         'minStart': 'Start minimized', //minStartCheckText
>         'updateAvailable': 'Update available',
>         'version': 'Version',
>         'available': 'is available for download on GitHub',
>         'download': 'Download',
>         'later': 'Later',
>         'quran': "Qur'an",
>         'font': 'Font',
>         'fontsize': 'Font size',
>         'translation': 'Translation',
>         'showTrans': 'Show translation',
>         'diffLang': 'Different language from app',
>         'transliteration': 'Transliteration',
>         'showTransliteration': 'Show transliteration',
>         'previous': 'Previous Surah',
>         'next': 'Next Surah',
>         'weather': 'Weather',
>         'showWeather': 'Show weather',
>         'units': 'Units',
>         'celsius': 'Celsius',
>         'kelvin': 'Kelvin',
>         'fahrenheit': 'Fahrenheit',
>         'playDua': "Play Du'a after Adhan",
>         'open': 'Open',
>         'quit': 'Quit',
>         'ahmedNufeis': 'Ahmed Al-Nufais',
>         'customFajr': 'Custom Fajr Adhan',
>         'recitation': 'Recitation',
>         'reciter': 'Reciter',
>         "customTimes": "Custom Times",
>         "enableCustomTimes" : "Enable custom times",
>         "jumuah" : "Jumuah",
>         "jumuahTime": "Jumuah Time",
>         "enableJumuahTime": "Enable Jumuah Time",
>         "shortAllahuAkbar": "Short sound - Mishary Rashid Alafasy",
>         "hijriAdjTitle" : "Hijri date adjustments",
>         "hijriAdjText" : "Hijri date difference",
> 
>     },
> 
> You have to translate what is after the : and between "" only. For example, on the first line, you should translate the "Settings".
> 
> Jazzaka Lahu khairan!
> If you have any questions, don't hesitate
> ```

I'm doing it but can you add Shia to madhab section?

**Comment by DBChoco** [comment]
If you want the shia praying times, you can have that in the in the calculation methods in the app. The Madhab has nothing to do with it, besides how Asr time is calculated
You can even add your own angles if you want to follow a local calculation method or madjid.
