### ISSUE TITLE
custom adhan times does not work

### ISSUE THREAD

**Issue by meypod** [DBChoco/Muezzin#24]
I'm on windows 10, and enabling and setting the custom times does not take effect (is not changed on main screen)

please tell me if you need more info

**Comment by DBChoco** [comment]
Can you send screen shots as well as relevant messages that show on the console please ? (for console press Crtl+shift+i, or in View - Toggle Console Tools (in the upper bar))

**Comment by DBChoco** [comment]
Also, please note that if you do not change the time, meaning if the default 12:00 AM is not changed, it will not take it into account.
This is so that all the times are not changed if you only need to change 1.

**Comment by meypod** [comment]
I checked console, there was no error

**Comment by meypod** [comment]
![image](https://github.com/DBChoco/Muezzin/assets/106489260/e61978b2-c23a-4705-b6f2-a5c5ccd1a971)

**Comment by meypod** [comment]
![image](https://github.com/DBChoco/Muezzin/assets/106489260/adf98b25-7072-4cfd-b895-6979be9019c6)

**Comment by meypod** [comment]
yeah I think I had adjustments as well

**Comment by meypod** [comment]
![image](https://github.com/DBChoco/Muezzin/assets/106489260/1c0757b6-5e5f-48bb-94c1-a4614c192364)

**Comment by meypod** [comment]
Also Asia/Tehran time zone must be updated, I don't know what library you use, but right now Asia/Tehran no longer has DST, so currently app is 1 hour ahead

**Comment by DBChoco** [comment]
That's strange, can you tell me how much is the delay between what you type and what you get ?
The timezone problem seems like it'll need much more work, InshaAllah I'll do it another day.
I'll have to go so I'll keep answering and working tomorrow inshaAllah, Jazzaka Lahu khairan for all the suggestions today.
Assalam Alaykoum

**Comment by meypod** [comment]
entered: 22:45
      got : 20:15

**Comment by DBChoco** [comment]
Solved the problem Alhamdoulillah, I had to disable timezone conversion for times entered manually. It should be good now inshaAllah

**Comment by DBChoco** [comment]
Fixed with this https://github.com/DBChoco/Muezzin/commit/4ba09484388d298ff636eeb020d7802edb0f64ad
Jazzaka  Lahu khairan
