### ISSUE TITLE
put "..." behind the verse quote ?

### ISSUE THREAD

**Issue by meypod** [DBChoco/Muezzin#25]
since it's from the end of the verse, to let people know it was cut, maybe put "..." behind the text ?

**Comment by DBChoco** [comment]
Jazzaka Lahu khairan, it is true that putting it just like this, it might make people think that it is the whole verse. I've changed it locally, inshaAllah I'll push the changes soon and close the issue.

**Comment by DBChoco** [comment]
Fixed with this https://github.com/DBChoco/Muezzin/commit/4ba09484388d298ff636eeb020d7802edb0f64ad
Jazzaka  Lahu khairan
