### ISSUE TITLE
Asia/Tehran time zone is 1 hour ahead

### ISSUE THREAD

**Issue by meypod** [DBChoco/Muezzin#27]
as of this year Asia/Tehran no longer has DST
but the app is 1 hour ahead

my first guess is that the electron package is outdated, because it seems you use 'toLocaleString'

try updating electron and other dependencies accordingly and this problem should be fixed insha'allah

**Comment by meypod** [comment]
I think there's also other countries that had DST changes recent years, so this should be an important update overall

**Comment by DBChoco** [comment]
Assalam Alaykoum, indeed updating all the depencendies fixed the problem, electron was very outdated
![image](https://github.com/DBChoco/Muezzin/assets/44785461/637961da-93db-4ad5-a985-58427aa56fce)

**Comment by DBChoco** [comment]
Fixed with this https://github.com/DBChoco/Muezzin/commit/4ba09484388d298ff636eeb020d7802edb0f64ad
Jazzaka  Lahu khairan
