### ISSUE TITLE
add sunset and it's adjustment

### ISSUE THREAD

**Issue by meypod** [DBChoco/Muezzin#28]
in some methods sunset time is not the same as the maghrib time

it would be nice to have a settings to show it and have it in the adjustments

in case you want to do it, you have to patch the adhan-js library to do it
you can do so by using [patch-package](https://www.npmjs.com/package/patch-package)

you can also use the patch I made for my own app from [here](https://github.com/meypod/al-azan/blob/4858e5b5d5a58f6ed944db6640d7de0d0bb5a281/patches/adhan%2B4.4.3.patch) and put it inside the `patches` directory, so `patch-package` can pick it up
my patch contains a fix for some days that js dates don't work as expected (because of DST), you can make your own patch if you are not comfortable with it

**Comment by DBChoco** [comment]
Assalam Alaykoum ! For now I'm really short on time, so I'll leave this be for now. Jazzaka Lahu Khairan.

**Comment by DBChoco** [comment]
Assalam Alaykoum,
it seems like this issue doesn't attract much attention and isn't really worth all the effort.
Sorry but it seems like I'll have to put it to the side (for now inshaAllah); I'll reopen this issue if more opinions arise.
