### ISSUE TITLE
Add location search

### ISSUE THREAD

**Issue by meypod** [DBChoco/Muezzin#29]
currently you have to enter coordinates to get the correct times
it would be nice if you added city search to the app

there's two ways you can achieve this:
1. use an online api to search the country and city name
2. use offline limited data

the downside of second way is that it adds ~5 mb to the app size (~12mb uncompressed), and doesn't contain all cities all over the world, but has a good coverage

I did the second way myself in my app, and I can help you port the data and search method I use into your app, if you like

**Comment by DBChoco** [comment]
It's a good suggestion, I'll inshaAllah do it once I get some free time, since this is quite a big change.
