### ISSUE TITLE
Time issue with the latest version

### ISSUE THREAD

**Issue by GaMeIsNtOvEr** [DBChoco/Muezzin#32]
Hello after upgrading to the latest version it seems Asia/Tehran timezone has been changed to a wrong timezone. it is one hour higher than the real time. as an example:  the real time is 3PM and it shows 4 PM.
Im not sure if its my issue or the app issue since the timezone was fine in the previous version but after i switched it got changed(I've checked the settings and everything was set correctly).
Thats not really a weird issue since even windows used to calculate the tehran timezone wrong and thats because of the new year in iran which used to make the time go one hour higher but when this year got started they've planned not to do this.
To fix that, if you're using a api to get tehran timezone i believe you need to change the api to somewhere else atleast for tehran. but if you're getting the tehran timezone without any api just make it one hour lower. as you can see the real time in tehran is on down. and muezzin one is in the app.
![image](https://github.com/DBChoco/Muezzin/assets/90923475/e061730d-00c0-43d5-acee-f11c33c0fe6e)

Sorry it got a bit long. if only i was a javascript developer so i would be able to contribute. however thanks for your great app it deserves more stars

**Comment by GaMeIsNtOvEr** [comment]
it seems there was another issue that was facing this. ig i gotta try building the sources so might it be fixed

**Comment by DBChoco** [comment]
Yes someone came to me with the same issue, so if you could try to build it and see if it is fixed.
Sorry if I didn't push the changes to the latest version, I'm super ultra busy these past few weeks ....

**Comment by DBChoco** [comment]
Assalam Alaykoum brother, can you try this please ? https://github.com/DBChoco/Muezzin/releases/tag/v2.6.0

**Comment by GaMeIsNtOvEr** [comment]
Sure i'll give it a try and will lyk

**Comment by GaMeIsNtOvEr** [comment]
> Assalam Alaykoum brother, can you try this please ? https://github.com/DBChoco/Muezzin/releases/tag/v2.6.0

yeah the time was fixed now thanks

**Comment by DBChoco** [comment]
No problem, if yo have any more issues feel free to contact me.
Salam

**Comment by GaMeIsNtOvEr** [comment]
btw custom adhan seems to be broken

**Comment by DBChoco** [comment]
Correct, seems like updating electron broke the audio, somehow ...
I'll open a new issue inshaAllah. Jazzaka Lahu khairan.

**Comment by DBChoco** [comment]
Fixed

**Comment by GaMeIsNtOvEr** [comment]
so could you give me the new build if possible? i do not have yarn to build it by my own

**Comment by DBChoco** [comment]
Sure, it's just on the release page: https://github.com/DBChoco/Muezzin/releases/tag/v2.6.0

**Comment by GaMeIsNtOvEr** [comment]
tyty
