### ISSUE TITLE
persian/farsi language and time zone adjust

### ISSUE THREAD

**Issue by kia1349** [DBChoco/Muezzin#34]
Hello and thank you for this complete program
If possible, add Persian language to the program
The time zone of Iran has changed since this year, and if possible, a feature can be added to the program so that the time zone can be applied manually
Now in Iran, prayer times are shown one hour ahead
For example, Fajr shows 05:12 AM instead of 04:12 AM
In the Qur'an section, when I select any surah, it shows only one verse of it
I would be very grateful if you could guide me in this matter as well as the audio transmission of the Quran
If possible, add the possibility of adding Quran and Persian translation of Quran manually in the program
When we go to the settings, the back button does not work
I am at your service for any help I can get for Farsi
kia1349@gmail.com

Your reward is with God
Thank you for your good program

**Comment by DBChoco** [comment]
Assalam Alaykoum,
can you check this beta release ? I think it has many of the things you asked for: 
https://github.com/DBChoco/Muezzin/releases/tag/v2.6.

**Comment by kia1349** [comment]
thanks brother
page can not find

**Comment by DBChoco** [comment]
Sorry, it was the wrong link https://github.com/DBChoco/Muezzin/releases/tag/v2.6.0

**Comment by DBChoco** [comment]
The issue should be fixed inshaAllah, if you have any more suggestions please feel free to open a new issue ! Assalam Alaykoum & Jazzaka Lahu khairan.

**Comment by kia1349** [comment]
thanks alot my bro
اسعدااله اوقاتکم خیرا :)
