### ISSUE TITLE
Bug report and some suggestions on v2.6.0 

### ISSUE THREAD

**Issue by GaMeIsNtOvEr** [DBChoco/Muezzin#35]
Hello it seems that 2.6.0 has some issues with playing adhan as i said in the past and muezzin media player is opened for no reason on muezzin starts. also could you please add Asia/Mashhad adhan times to muezzin?

**Comment by DBChoco** [comment]
Salam, can you check now, I think I forgot previously to update the release.
About the Asia/mashhad, I didn't make the timezone list myself, it's imported.

**Comment by DBChoco** [comment]
The issue should be fixed inshaAllah, if you have any more suggestions please feel free to open a new issue ! Assalam Alaykoum & Jazzaka Lahu khairan.
