### ISSUE TITLE
Prayers hours is wrong ?

### ISSUE THREAD

**Issue by Watynecc** [DBChoco/Muezzin#44]
Salam ! I like to thanks you for this amazing application while I'm working in my pc

For some reason my french website is diffrent from muzzin one as you can see below :

![image](https://github.com/DBChoco/Muezzin/assets/64525273/0c8161e1-7c67-4e52-8fb6-87aa763a1572)
![image](https://github.com/DBChoco/Muezzin/assets/64525273/f71bb968-d5f1-4142-896c-78a8370b0bb6)

When I check the coordonnate I see this
for Muezzin
![image](https://github.com/DBChoco/Muezzin/assets/64525273/8570643a-d606-4231-9cbd-39b857efa843)

For the french website 
![image](https://github.com/DBChoco/Muezzin/assets/64525273/89979e4e-5e15-481f-873e-0d5c4cd1f5ff)

So I don't know which one are true but I know that all my acquaintances use it. There's the link of the [https://www.guidemusulman.com/horaires-prieres/mensuel/ville/9468/pontarlier-25300](website)

**Comment by DBChoco** [comment]
Wa Alaykoum Assalam wa Rahmatou Lahi wa Baraketu

Please check the calculation methods, there are many many depending on your location. It depends on how your local place/website calculates the tables.

I believe the default used by Muezzin is 18° or something like that, but you website only uses 12/15°; perhaps try to change that in the settings.

If you have a flat place around you, go there and see at what time you see dawn, then you can check which one is best for you; or you can ask you local mosque.

I hope this helps !

**Comment by Watynecc** [comment]
Thanks you ! Sorry for bothering you 🥲

**Comment by DBChoco** [comment]
No issues at all !
Assalam Alaykoum.
