### ISSUE TITLE
Not working on Fedora 39 Gnome 45.

### ISSUE THREAD

**Issue by ghost** [DBChoco/Muezzin#46]
Thank you for the nice app. Unfortunately, first time it launched properly and I set the city and other things. After that, I noticed both fans of my laptop are running at nearly at 70% of the speed continuously until I restarted and uninstalled the app. I guess something is wrong with the electron GPU renderer.

**Comment by DBChoco** [comment]
Assalam Alaykoum,
Sorry for the late answer, I couldn't find the time to reply.

What versions have you tried ? How did you install it ?

Perhaps you can try this https://github.com/DBChoco/Salawat 
A small clone I made that is much lighter on resources, but less powerful. Alhamdoulillah.

**Comment by ghost** [comment]
Alykum Assalam,
Thank you for the reply. No problem. I tried v 2.6.0 from the flathub and installed it using gnome software. I guess my pc (10th gen intel H + Nvidia GTX 1660 Ti) is eligible to run the full version. Not only that, but also tried Salawat, but there was something wrong with the timezone and method of calculation (I don't exactly remember). Anyway, brother, thanks for everything. May Allah bless you for the good work.
